---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
    driver:
      box: centos-71
      box_url: https://deploy.gmti.gbahn.net/Images/centos7/vagrant/centos71-cloud-1.0.0.box
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[ruby-support::default]
    attributes:
