driver:
  name: vagrant
  customize:
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
    driver:
      box: centos-71
      box_url: https://deploy.gmti.gbahn.net/Images/centos7/vagrant/centos71-cloud-1.0.0.box
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[ruby-deployment-support::default]
    attributes:
      ruby-deployment-support:
        server:
            environment: 'development'
        odbc:
            install: false
